### ISSUE TITLE
Couldn't run the new updated code

### ISSUE THREAD

**Issue by chandrad** [itaysason/Mix-MMM#8]
I am encountering the error. 

>> snakemake --cores all

Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from src.utils import save_json, get_cosmic_signatures, get_data
ModuleNotFoundError: No module named 'src.utils'

**Comment by chandrad** [comment]
Please upload the runnable code. Thanks for all the help.

**Comment by itaysason** [comment]
Use python >= 3.7, or simply use the environment.yml to create a virtual env. The code should work with the following command (for example):
python main.py train_model --dataset MSK-ALL --num_clusters 9 --use_cosmic 0 --num_signatures 3 --random_seed 140296 --max_iterations 1000

**Comment by chandrad** [comment]
I fired the command an hour ago. It's still running. Approximately how much time will it take? Can I reproduce the results as per the paper in figure 4: De-novo signature discovery from MSK-IMPACT panel data. Will it generate the plots?
